import { describe, it, expect } from "vitest";
import { buildAnalyzePromptVi, buildAnalyzePromptEn, buildParseCvPrompt } from "../../services/ai/prompts";

const mockJdSection = "<!-- JD: Senior Frontend Developer -->";

describe("prompts — buildAnalyzePromptVi", () => {
  it("returns a non-empty string", () => {
    const result = buildAnalyzePromptVi({ jdSection: mockJdSection });
    expect(result).toBeTruthy();
    expect(typeof result).toBe("string");
  });

  it("contains the JD section text", () => {
    const result = buildAnalyzePromptVi({ jdSection: mockJdSection });
    expect(result).toContain(mockJdSection);
  });

  it("contains Vietnamese instructions", () => {
    const result = buildAnalyzePromptVi({ jdSection: mockJdSection });
    expect(result).toContain("TIẾNG VIỆT");
    expect(result).toContain("chuyên gia tuyển dụng");
  });

  it("contains key analysis instructions in Vietnamese", () => {
    const result = buildAnalyzePromptVi({ jdSection: mockJdSection });
    expect(result).toContain("Google XYZ");
    expect(result).toContain("MM/YYYY");
    expect(result).toContain("detailedComparison");
  });

  it("classifies JD requirements as required vs nice-to-have and requests a formatAssessment", () => {
    const result = buildAnalyzePromptVi({ jdSection: mockJdSection });
    expect(result).toContain("BẮT BUỘC");
    expect(result).toContain("ƯU TIÊN");
    expect(result).toContain("formatAssessment");
    expect(result).toContain("analysisAvailable");
  });

  // fullRewrittenCV and Parsed CV extraction are generated by separate
  // background prompts (buildRewritePromptVi in _server-lib/ai/rewriteService.ts
  // and buildParseCvPrompt below) — not part of the main analyze call.
});

describe("prompts — buildAnalyzePromptEn", () => {
  it("returns a non-empty string", () => {
    const result = buildAnalyzePromptEn({ jdSection: mockJdSection });
    expect(result).toBeTruthy();
    expect(typeof result).toBe("string");
  });

  it("contains the JD section text", () => {
    const result = buildAnalyzePromptEn({ jdSection: mockJdSection });
    expect(result).toContain(mockJdSection);
  });

  it("contains English instructions", () => {
    const result = buildAnalyzePromptEn({ jdSection: mockJdSection });
    expect(result).toContain("ENGLISH");
    expect(result).toContain("ATS (Applicant Tracking System)");
  });

  it("contains key analysis instructions in English", () => {
    const result = buildAnalyzePromptEn({ jdSection: mockJdSection });
    expect(result).toContain("Google XYZ");
    expect(result).toContain("MM/YYYY");
    expect(result).toContain("detailed comparison table");
  });

  it("classifies JD requirements as REQUIRED vs NICE-TO-HAVE and requests a formatAssessment", () => {
    const result = buildAnalyzePromptEn({ jdSection: mockJdSection });
    expect(result).toContain("REQUIRED");
    expect(result).toContain("NICE-TO-HAVE");
    expect(result).toContain("formatAssessment");
    expect(result).toContain("analysisAvailable");
  });
});

describe("prompts — buildParseCvPrompt", () => {
  it("returns a non-empty string for both languages", () => {
    expect(buildParseCvPrompt({ jdSection: mockJdSection, language: "vi" })).toBeTruthy();
    expect(buildParseCvPrompt({ jdSection: mockJdSection, language: "en" })).toBeTruthy();
  });

  it("contains the JD section text", () => {
    const result = buildParseCvPrompt({ jdSection: mockJdSection, language: "vi" });
    expect(result).toContain(mockJdSection);
  });

  it("contains CV extraction instructions in Vietnamese", () => {
    const result = buildParseCvPrompt({ jdSection: mockJdSection, language: "vi" });
    expect(result).toContain("Kinh nghiệm làm việc");
    expect(result).toContain("technical_skills");
    expect(result).toContain("relevant_score");
    expect(result).toContain("MM/YYYY");
  });

  it("contains CV extraction instructions in English", () => {
    const result = buildParseCvPrompt({ jdSection: mockJdSection, language: "en" });
    expect(result).toContain("Work Experience");
    expect(result).toContain("technical_skills");
    expect(result).toContain("relevant_score");
    expect(result).toContain("MM/YYYY");
  });

  it("defaults to Vietnamese when language is omitted", () => {
    const result = buildParseCvPrompt({ jdSection: mockJdSection });
    expect(result).toContain("Trích xuất");
  });
});